export const Projects = [
  {
    id: "1",
    name: "NuKenzie",
    language: "JavaScript",
    description: "Descrição do projeto 2.",
    owner: "Leandro",
    vercelLink: "https://m3-entrega-s2-template-nu-kenzie-leandro-goncalves.vercel.app/",
    codeLink: "https://github.com/Kenzie-Academy-Brasil-Developers/m3-entrega-s2-template-nu-kenzie_Leandro-Goncalves",
  },
  {
    id: "2",
    name: "FoodApp",
    language: "JavaScript",
    description: "Descrição do projeto 4.",
    owner: "Leandro",
    vercelLink: "https://extra-projeto-food-app-landing-page.vercel.app/",
    codeLink: "https://github.com/Kenzie-Academy-Brasil-Developers/Extra-Projeto-Food-App-Landing-Page",
  },
  {
    id: "3",
    name: "Hamburgueria Kenzie",
    language: "JavaScript",
    description: "Descrição do projeto 3.",
    owner: "Leandro",
    vercelLink: "https://react-entrega-s3-template-hamburgueria-leandro-goncalves.vercel.app/",
    codeLink: "https://github.com/Kenzie-Academy-Brasil-Developers/react-entrega-s3-template-hamburgueria-Leandro-Goncalves",
  },
  {
    id: "4",
    name: "KenzieHub",
    language: "JavaScript",
    description: "Descrição do projeto 1.",
    owner: "Leandro",
    vercelLink: "https://m3-react-entrega-kenzie-hub-leandro-goncalves.vercel.app/",
    codeLink: "https://github.com/Kenzie-Academy-Brasil-Developers/m3-react-entrega-kenzie-hub-Leandro-Goncalves",
  },
];
